// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: checks.sql

package sqlc

import (
	"context"
)

const createCheck = `-- name: CreateCheck :one
INSERT INTO checks (monitor_id, status_code, response_ms, is_up, error)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, monitor_id, status_code, response_ms, is_up, error, checked_at
`

type CreateCheckParams struct {
	MonitorID  int64  `json:"monitor_id"`
	StatusCode int32  `json:"status_code"`
	ResponseMs int32  `json:"response_ms"`
	IsUp       bool   `json:"is_up"`
	Error      string `json:"error"`
}

func (q *Queries) CreateCheck(ctx context.Context, arg CreateCheckParams) (Check, error) {
	row := q.db.QueryRow(ctx, createCheck,
		arg.MonitorID,
		arg.StatusCode,
		arg.ResponseMs,
		arg.IsUp,
		arg.Error,
	)
	var i Check
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.StatusCode,
		&i.ResponseMs,
		&i.IsUp,
		&i.Error,
		&i.CheckedAt,
	)
	return i, err
}

const getLatestCheckByMonitor = `-- name: GetLatestCheckByMonitor :one
SELECT id, monitor_id, status_code, response_ms, is_up, error, checked_at FROM checks
WHERE monitor_id = $1
ORDER BY checked_at DESC
LIMIT 1
`

func (q *Queries) GetLatestCheckByMonitor(ctx context.Context, monitorID int64) (Check, error) {
	row := q.db.QueryRow(ctx, getLatestCheckByMonitor, monitorID)
	var i Check
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.StatusCode,
		&i.ResponseMs,
		&i.IsUp,
		&i.Error,
		&i.CheckedAt,
	)
	return i, err
}

const getLatestChecksForAllMonitors = `-- name: GetLatestChecksForAllMonitors :many
SELECT DISTINCT ON (monitor_id) id, monitor_id, status_code, response_ms, is_up, error, checked_at
FROM checks
ORDER BY monitor_id, checked_at DESC
`

func (q *Queries) GetLatestChecksForAllMonitors(ctx context.Context) ([]Check, error) {
	rows, err := q.db.Query(ctx, getLatestChecksForAllMonitors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Check
	for rows.Next() {
		var i Check
		if err := rows.Scan(
			&i.ID,
			&i.MonitorID,
			&i.StatusCode,
			&i.ResponseMs,
			&i.IsUp,
			&i.Error,
			&i.CheckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChecksByMonitor = `-- name: ListChecksByMonitor :many
SELECT id, monitor_id, status_code, response_ms, is_up, error, checked_at FROM checks
WHERE monitor_id = $1
ORDER BY checked_at DESC
LIMIT $2
`

type ListChecksByMonitorParams struct {
	MonitorID int64 `json:"monitor_id"`
	Limit     int32 `json:"limit"`
}

func (q *Queries) ListChecksByMonitor(ctx context.Context, arg ListChecksByMonitorParams) ([]Check, error) {
	rows, err := q.db.Query(ctx, listChecksByMonitor, arg.MonitorID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Check
	for rows.Next() {
		var i Check
		if err := rows.Scan(
			&i.ID,
			&i.MonitorID,
			&i.StatusCode,
			&i.ResponseMs,
			&i.IsUp,
			&i.Error,
			&i.CheckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
