// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Check struct {
	ID         int64              `json:"id"`
	MonitorID  int64              `json:"monitor_id"`
	StatusCode int32              `json:"status_code"`
	ResponseMs int32              `json:"response_ms"`
	IsUp       bool               `json:"is_up"`
	Error      string             `json:"error"`
	CheckedAt  pgtype.Timestamptz `json:"checked_at"`
}

type Monitor struct {
	ID          int64              `json:"id"`
	Url         string             `json:"url"`
	Name        string             `json:"name"`
	IntervalSec int32              `json:"interval_sec"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}
