// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: monitors.sql

package sqlc

import (
	"context"
)

const createMonitor = `-- name: CreateMonitor :one
INSERT INTO monitors (url, name, interval_sec)
VALUES ($1, $2, $3)
RETURNING id, url, name, interval_sec, created_at
`

type CreateMonitorParams struct {
	Url         string `json:"url"`
	Name        string `json:"name"`
	IntervalSec int32  `json:"interval_sec"`
}

func (q *Queries) CreateMonitor(ctx context.Context, arg CreateMonitorParams) (Monitor, error) {
	row := q.db.QueryRow(ctx, createMonitor, arg.Url, arg.Name, arg.IntervalSec)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Name,
		&i.IntervalSec,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMonitor = `-- name: DeleteMonitor :exec
DELETE FROM monitors WHERE id = $1
`

func (q *Queries) DeleteMonitor(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteMonitor, id)
	return err
}

const getMonitor = `-- name: GetMonitor :one
SELECT id, url, name, interval_sec, created_at FROM monitors WHERE id = $1
`

func (q *Queries) GetMonitor(ctx context.Context, id int64) (Monitor, error) {
	row := q.db.QueryRow(ctx, getMonitor, id)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Name,
		&i.IntervalSec,
		&i.CreatedAt,
	)
	return i, err
}

const listMonitors = `-- name: ListMonitors :many
SELECT id, url, name, interval_sec, created_at FROM monitors ORDER BY id ASC
`

func (q *Queries) ListMonitors(ctx context.Context) ([]Monitor, error) {
	rows, err := q.db.Query(ctx, listMonitors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Monitor
	for rows.Next() {
		var i Monitor
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Name,
			&i.IntervalSec,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
