// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	CreateCheck(ctx context.Context, arg CreateCheckParams) (Check, error)
	CreateMonitor(ctx context.Context, arg CreateMonitorParams) (Monitor, error)
	DeleteMonitor(ctx context.Context, id int64) error
	GetLatestCheckByMonitor(ctx context.Context, monitorID int64) (Check, error)
	GetLatestChecksForAllMonitors(ctx context.Context) ([]Check, error)
	GetMonitor(ctx context.Context, id int64) (Monitor, error)
	ListChecksByMonitor(ctx context.Context, arg ListChecksByMonitorParams) ([]Check, error)
	ListMonitors(ctx context.Context) ([]Monitor, error)
}

var _ Querier = (*Queries)(nil)
